### ISSUE TITLE
seem like a bug for sequential.py 

### ISSUE THREAD

**Issue by Linyi617** [Guanyu-Lin/MAN#2]
when I run sequential.py，there is a bug as below：

System version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
Tensorflow version: 1.14.0
start experiment

Traceback (most recent call last):
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 2 is not in [0, 2)
         [[{{node sequential/embedding_lookup_7}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/d/MAN/examples/00_quick_start/sequential.py", line 334, in <module>
    app.run(main)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/d/MAN/examples/00_quick_start/sequential.py", line 300, in main
    model = model.fit(train_fileA, train_fileB, valid_fileA, valid_fileB, valid_num_ngs=valid_num_ngs, eval_metric=eval_metric, vm=vm, tb=tb, pretrain=flags_obj.pretrain) 
  File "/data/d/MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py", line 334, in fit
    epoch_lossA = self.batch_trainA(file_iteratorA, train_sess, vm, tb, valid_fileA, valid_num_ngs)
  File "/data/d/MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py", line 173, in batch_trainA
    step_result = self.trainA(train_sess, batch_data_input)
  File "/data/d/MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py", line 146, in trainA
    return super(SequentialBaseModel, self).trainA(sess, feed_dict)
  File "/data/d/MAN/reco_utils/recommender/deeprec/models/base_model.py", line 487, in trainA
    feed_dict=feed_dict,
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/data/d/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 2 is not in [0, 2)
         [[node sequential/embedding_lookup_7 (defined at /MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py:802) ]]

can you give me some advice to fix it， Thanks~

**Comment by Linyi617** [comment]
I want to know your version of TensorFlow。
according to your README，I use 1.12.3，but this bug appears：


sorted_S_flatten = tf.sort(S_flatten, direction='DESCENDING', axis=-1) # B*L -> B*L
AttributeError: module 'tensorflow' has no attribute 'sort'

**Comment by Guanyu-Lin** [comment]
> I want to know your version of TensorFlow。 according to your README，I use 1.12.3，but this bug appears：
> 
> sorted_S_flatten = tf.sort(S_flatten, direction='DESCENDING', axis=-1) # B_L -> B_L AttributeError: module 'tensorflow' has no attribute 'sort'

Thanks for your reaching out, I see my tensorflow is '1.13.1'.

**Comment by Guanyu-Lin** [comment]
> [[node sequential/embedding_lookup_7 (defined at /MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py:802) ]]

Have you solve this problem? It seems the bug is located at '[[node sequential/embedding_lookup_7 (defined at /MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py:802) ]]'. But I never encounter this bug, maybe you can use pdb.set_trace() to find more information about the bug?

**Comment by Linyi617** [comment]
> > I want to know your version of TensorFlow。 according to your README，I use 1.12.3，but this bug appears：
> > sorted_S_flatten = tf.sort(S_flatten, direction='DESCENDING', axis=-1) # B_L -> B_L AttributeError: module 'tensorflow' has no attribute 'sort'
> 
> Thanks for your reaching out, I see my tensorflow is '1.13.1'.

thank you！but if I use 1.13.1, a new bug appears:

System version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
Tensorflow version: 1.13.1
start experiment

Traceback (most recent call last):
  File "/data/dongyan/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2024, in ones
    tensor_shape.TensorShape(shape))
  File "/data/dongyan/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 325, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)

can you give the total env list? thank you so much~

**Comment by Guanyu-Lin** [comment]
> > > I want to know your version of TensorFlow。 according to your README，I use 1.12.3，but this bug appears：
> > > sorted_S_flatten = tf.sort(S_flatten, direction='DESCENDING', axis=-1) # B_L -> B_L AttributeError: module 'tensorflow' has no attribute 'sort'
> > 
> > 
> > Thanks for your reaching out, I see my tensorflow is '1.13.1'.
> 
> thank you！but if I use 1.13.1, a new bug appears:
> 
> System version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0] Tensorflow version: 1.13.1 start experiment
> 
> Traceback (most recent call last): File "/data/dongyan/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2024, in ones tensor_shape.TensorShape(shape)) File "/data/dongyan/miniconda3/envs/MAN/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 325, in _tensor_shape_tensor_conversion_function "Cannot convert a partially known TensorShape to a Tensor: %s" % s) ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)
> 
> can you give the total env list? thank you so much~

Sorry, I have add my env list i.e. requirement.yaml in the github. Here is the link for your convenience: https://github.com/Guanyu-Lin/MAN/blob/main/requirement.yaml.
