### ISSUE TITLE
a problem for sequence.py

### ISSUE THREAD

**Issue by elaine-zmz** [Guanyu-Lin/MAN#4]
when I run sequential.py，there is a bug. The location where this bug appears is line 129 of sequence.py: 

File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 129, in _encoder
    threshold_score = tf.gather_nd(sorted_S_flatten, tf.expand_dims(tf.cast(to_keep_edge, tf.int32), -1), batch_dims=1) # indices[:-1]=(B) + data[indices[-1]=() --> (B)
TypeError: gather_nd() got an unexpected keyword argument 'batch_dims'

I tried searching for similar questions but didn't find a solution. The environment I used is tensorflow-gpu1.13.1 given by the author.

can you give me some advice to fix it, Thanks~

**Comment by Guanyu-Lin** [comment]
You can try change gather_nd with gather?

**Comment by elaine-zmz** [comment]
I just tried, but there is also a bug, similar to the former.

File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 129, in _encoder
    threshold_score = tf.gather(sorted_S_flatten, tf.expand_dims(tf.cast(to_keep_edge, tf.int32), -1), batch_dims=1) # indices[:-1]=(B) + data[indices[-1]=() --> (B)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
TypeError: gather() got an unexpected keyword argument 'batch_dims'
We

**Comment by Guanyu-Lin** [comment]
how about replace betach_dims = 1 with axis = 1

**Comment by elaine-zmz** [comment]
Thank you. But another bug appears. Could you give me more advice to fix it? Maybe this problem is because of my environment?

System version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
Tensorflow version: 1.13.1
start experiment

Traceback (most recent call last):
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2024, in ones
    tensor_shape.TensorShape(shape))
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 325, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/00_quick_start/sequential.py", line 331, in <module>
    app.run(main)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "examples/00_quick_start/sequential.py", line 268, in main
    model = get_model(flags_obj, model_path, summary_path, pretrain_path, finetune_path, user_vocab, item_vocab, cate_vocab, train_num_ngs, data_path)
  File "examples/00_quick_start/sequential.py", line 149, in get_model
    model = SURGEModel(hparams, input_creator, seed=RANDOM_SEED)
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 52, in __init__
    super().__init__(hparams, iterator_creator, seed=None)
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py", line 49, in __init__
    super().__init__(hparams, iterator_creator, graph=self.graph, seed=seed)
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/base_model.py", line 57, in __init__
    self.logitA, self.logitB, self.attn_weight_A, self.attn_weight_B= self._build_graph()
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py", line 135, in _build_graph
    model_outputA, model_outputB, model_output, attn_weight_A, attn_weight_B = self._build_seq_graph()
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 54, in _build_seq_graph
    self.local_seqA, self.local_PE_embA, final_stateA,  graph_readoutA, real_maskA, self.auxiliary_lossA = self._encoder(self.item_history_embedding_A, self.cate_history_embedding_A, self.position_embedding_A, "A")
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 136, in _encoder
    X, A, graph_readout, alphas, tmp_mask, auxiliary_loss = self._interest_fusion_extraction_new(X, A, mask, layer=l, reuse=reuse)
  File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 291, in _interest_fusion_extraction_new
    A_bool = A_bool * (tf.ones([A.shape.as_list()[1],A.shape.as_list()[1]]) - tf.eye(A.shape.as_list()[1])) + tf.eye(A.shape.as_list()[1])
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2027, in ones
    shape = ops.convert_to_tensor(shape, dtype=dtypes.int32)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 466, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/zmz/miniconda3/envs/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 371, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got None of type '_Message' instead.

**Comment by Guanyu-Lin** [comment]
The bug occurs at "File "/home/zmz/projects/MAN/reco_utils/recommender/deeprec/models/sequential/surge.py", line 291, in _interest_fusion_extraction_new
A_bool = A_bool * (tf.ones([A.shape.as_list()[1],A.shape.as_list()[1]]) - tf.eye(A.shape.as_list()[1])) + tf.eye(A.shape.as_list()[1])". Maybe you can try import pdb pdb.set_trace() before this line and print everything to check the bug.
